"""empty message

Revision ID: 8a106f7a986d
Revises: 6ca09d75c862
Create Date: 2020-03-30 21:50:48.752039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a106f7a986d'
down_revision = '6ca09d75c862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('num_evals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'num_evals')
    # ### end Alembic commands ###
